name: DEPLOY_PIPELINE_DEV

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

# deploy.yml env variable
env:
  S3_BUCKET_NAME: sequence-ting
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '19'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # Runs a set of commands using the runners shell
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      # Make a Zip file
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      # Upload our Zip file to S3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip
