name: Spring

on:
    pull_request:
        branches:
            - master
            - dev

env:
    PROPERTIES: src/main/resources/application.yaml

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup JDK 19
              uses: actions/setup-java@v3
              with:
                distribution: 'oracle'
                java-version: '19'
                cache: 'gradle'

            - name: Create properties
              run: echo "${{ secrets.PROPERTIES }}" > ${{ env.PROPERTIES }}

            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                arguments: build